spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: Adrress
    username: name
    password: password


  devtools:

    livereload:

      enabled: true

    thymeleaf:

      cache: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: Email
    password: Password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#server:
#  port: 8080
#security:
#  user:
#    name: user
#    password: 1234
#
#jpa:
#  hibernate:
#    ddl-auto: update
#  properties:
#    hibernate:
#      format_sql: true
#      show_sql: true
#
#profiles:
#  include: security
